name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".gitingore"
      - ".github/**"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".gitingore"
      - ".github/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check

    strategy:
      matrix:
        platform:
          - ubuntu-latest

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ runner.os }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose

      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: format code"
